### ISSUE TITLE
After upgrading APIM 2.1.0/2.2.0 to 3.1.0, Unable to login to the tenant admin account.

### ISSUE THREAD

**Issue by TheRasanjana** [wso2-extensions/apim-migration-resources#6]
**Description:**
After upgrading APIM 2.1.0 and 2.2.0 to 3.1.0, Unable to login to the tenant admin account. This issue is only observed when using Oracle databases.

### Steps to reproduce:

1. Configure APIM  2.1.0 or 2.2.0 with **Oracle as database** for AM_DB, REG_DB and UM_DB.
2. Populate data by creating Tenants, APIs and Applications
3. Proceed the Migration by following 2.1.0/2.2.0 to 3.1.0 Migration doc. (IS migration client version : wso2is-migration-1.0.96)
4. Navigate to publisher and login with Tenant's credentials.

### Actual Output 
- When trying to login to tenant through publisher or devportal, Invalid credentials error message will be displayed. 
- When trying to login to tenant through management console, following error is seen in error log.
ERROR - AuthenticationAdmin System error while Authenticating/Authorizing User : Error when handling event : PRE_AUTHENTICATION

[Debug_log_.txt](https://github.com/wso2-extensions/apim-migration-resources/files/4683762/Debug_log_Enabling_event_listner.txt)

**Comment by rmsamitha** [comment]
The root cause was that the registry versioning disabling scripts executed on reg db were not commited, within that DB connection session. So those DML changes were not reflected into the reg db. So it had caused missing a mapping entry in reg_resource_property table for the type property of the tenant's keystore jks file. After doing the migration with "committing" each oracle scripts, the issue can be fixed. 

Added a note in the docs with https://github.com/wso2/docs-apim/pull/1291/files
